baseURL = "https://newinh.me"
languageCode = "en-us"
title = "SeungHoon Shin"
theme = "awesome-identity"
# Enable Emoji emoticons support for page content
enableEmoji = true


## Profile Configurations
[params.profile]
  portrait = "/images/me.jpg"
  firstname = "Seunghoon"
  lastname = "Shin"
  title = "Software Enginner ∙ Back-end"
  bio = """1+ year experience in back-end development.

  Experienced embedded, Android, iOS development as a beginner, recently worked on project related to collecting data in fashion AI company. 

Open culture of IT industry was so impressive that I started developmenting software. 

As I got help and inspired, I want to be a engineer who can help. 

Main skills are Python, flask, MySQL now, but i'm ready to challenge other technical skills and accomplish projects."""


## Contacts Configurations
[params.contacts]
  email = "newinh90@gmail.com"
  github = "newinh"
  linkedin = "newinh"
  stackoverflow = "6933079"


## Actions Configurations
[[params.actions]]
  name = "Resume"
  url = "files/resume.pdf"


## Footer Configurations
[params.footer]
  copyright = "© 2019 Seunghoon Shin. [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)."
  poweredBy = true
