[build]
publish = "public"
command = "git submodule update --rebase --remote && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
